apiVersion: v1
kind: Namespace
metadata:
  name: vibes-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: vibes-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::897297231794:role/vibes-worker-irsa
