apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PLATFORM_REDIS_NAME}
  namespace: ${PLATFORM_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PLATFORM_REDIS_NAME}
  template:
    metadata:
      labels:
        app: ${PLATFORM_REDIS_NAME}
    spec:
      containers:
        - name: ${PLATFORM_REDIS_NAME}
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ${PLATFORM_REDIS_NAME}
  namespace: ${PLATFORM_NAMESPACE}
spec:
  selector:
    app: ${PLATFORM_REDIS_NAME}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
