apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${PLATFORM_SERVER_METRICS_CLUSTER_ROLE_NAME}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${PLATFORM_SERVER_METRICS_CLUSTER_ROLE_BINDING_NAME}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${PLATFORM_SERVER_METRICS_CLUSTER_ROLE_NAME}
subjects:
  - kind: ServiceAccount
    name: ${PLATFORM_SERVER_SERVICE_ACCOUNT_NAME}
    namespace: ${PLATFORM_NAMESPACE}
