apiVersion: v1
kind: Service
metadata:
  name: vibes-server
  namespace: vibes-platform
spec:
  type: ClusterIP
  selector:
    app: vibes-server
  ports:
    - name: http
      port: 80
      targetPort: 8000
