apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${PLATFORM_WORKER_CLUSTER_ROLE_NAME}
rules:
  - apiGroups: [""]
    resources: ["secrets", "services", "configmaps", "namespaces", "pods", "pods/log", "pods/status", "nodes", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${PLATFORM_WORKER_CLUSTER_ROLE_BINDING_NAME}
subjects:
  - kind: ServiceAccount
    name: ${PLATFORM_WORKER_SERVICE_ACCOUNT_NAME}
    namespace: ${PLATFORM_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: ${PLATFORM_WORKER_CLUSTER_ROLE_NAME}
  apiGroup: rbac.authorization.k8s.io
